import * as THREE from './three.module.js';
// Reader for the uncompressed static GLB assets used in this review.
export async function loadReference(url,skipTextures=false){
 const response=await fetch(url);if(!response.ok)throw Error('Model download failed: '+response.status);
 const bytes=await response.arrayBuffer(),dv=new DataView(bytes);if(dv.getUint32(0,true)!==0x46546c67)throw Error('Invalid GLB');
 let json,bin;for(let off=12;off<bytes.byteLength;){const n=dv.getUint32(off,true),kind=dv.getUint32(off+4,true);if(kind===0x4e4f534a)json=JSON.parse(new TextDecoder().decode(new Uint8Array(bytes,off+8,n)));if(kind===0x004e4942)bin=bytes.slice(off+8,off+8+n);off+=8+n;}
 const types={5126:Float32Array,5125:Uint32Array,5123:Uint16Array,5121:Uint8Array};const widths={SCALAR:1,VEC2:2,VEC3:3,VEC4:4};
 function attribute(i){const a=json.accessors[i],v=json.bufferViews[a.bufferView],Ctor=types[a.componentType],width=widths[a.type];if(!Ctor||!width)throw Error('Unsupported attribute');const start=(v.byteOffset||0)+(a.byteOffset||0);let array;if(v.byteStride&&v.byteStride!==Ctor.BYTES_PER_ELEMENT*width){array=new Ctor(a.count*width);for(let k=0;k<a.count;k++)array.set(new Ctor(bin,start+k*v.byteStride,width),k*width)}else array=new Ctor(bin,start,a.count*width);return new THREE.BufferAttribute(array,width,!!a.normalized)}
 const textures=[];
 if(!skipTextures)for(const tex of json.textures||[]){const im=json.images[tex.source],v=json.bufferViews[im.bufferView];const blob=new Blob([bin.slice(v.byteOffset||0,(v.byteOffset||0)+v.byteLength)],{type:im.mimeType});const uri=URL.createObjectURL(blob);try{const texture=await new THREE.TextureLoader().loadAsync(uri);texture.flipY=false;texture.colorSpace=THREE.SRGBColorSpace;textures.push(texture)}finally{URL.revokeObjectURL(uri)}}
 const materials=(json.materials||[{}]).map(m=>{const p=m.pbrMetallicRoughness||{},c=p.baseColorFactor||[1,1,1,1];return new THREE.MeshStandardMaterial({color:new THREE.Color(c[0],c[1],c[2]),map:textures[p.baseColorTexture?.index]||null,metalness:p.metallicFactor??1,roughness:p.roughnessFactor??1,side:m.doubleSided?THREE.DoubleSide:THREE.FrontSide})});
 let triangles=0;const nodes=json.nodes.map(n=>{const g=new THREE.Group();g.name=n.name||'Robot';if(n.matrix){g.matrix.fromArray(n.matrix);g.matrix.decompose(g.position,g.quaternion,g.scale)}else{if(n.translation)g.position.fromArray(n.translation);if(n.rotation)g.quaternion.fromArray(n.rotation);if(n.scale)g.scale.fromArray(n.scale)}if(n.mesh!==undefined)for(const p of json.meshes[n.mesh].primitives){const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',attribute(p.attributes.POSITION));if(p.attributes.TEXCOORD_0!==undefined)geometry.setAttribute('uv',attribute(p.attributes.TEXCOORD_0));if(p.attributes.NORMAL!==undefined)geometry.setAttribute('normal',attribute(p.attributes.NORMAL));if(p.indices!==undefined)geometry.setIndex(attribute(p.indices));if(!geometry.attributes.normal)geometry.computeVertexNormals();triangles+=(geometry.index?.count??geometry.attributes.position.count)/3;g.add(new THREE.Mesh(geometry,materials[p.material??0]));}return g});
 json.nodes.forEach((n,i)=>n.children?.forEach(c=>nodes[i].add(nodes[c])));const root=new THREE.Group();for(const i of json.scenes[json.scene||0].nodes)root.add(nodes[i]);root.updateMatrixWorld(true);const bounds=new THREE.Box3().setFromObject(root),size=bounds.getSize(new THREE.Vector3()),center=bounds.getCenter(new THREE.Vector3()),scale=3.15/size.y;
 const fitted=new THREE.Group();root.position.set(-center.x*scale,-bounds.min.y*scale,-center.z*scale);root.scale.setScalar(scale);fitted.add(root);return {root:fitted,materials,triangles};
}
